/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.antoniodiego.gertarefas.view.principal;

/**
 *
 * @author antonio
 */
public class JanelaPrincipalMatisse extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipalMatisse
     */
    public JanelaPrincipalMatisse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneLadoEsq = new javax.swing.JTabbedPane();
        painelListaTarefas1 = new br.com.antoniodiego.gertarefas.view.principal.PainelListaTarefas();
        tabPaneLadoDir = new javax.swing.JTabbedPane();
        painelFuncoes1 = new br.com.antoniodiego.gertarefas.view.principal.PainelFuncoes();
        painelAgendamentosMat1 = new br.com.antoniodiego.gertarefas.view.principal.PainelAgendamentosMat();
        painelNotificacoesM1 = new br.com.antoniodiego.gertarefas.view.principal.PainelNotificacoesM();
        painelInferior = new javax.swing.JPanel();
        painelBarraFerra = new javax.swing.JPanel();
        gruposETarefa = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        exportacao = new javax.swing.JToolBar();
        jButton8 = new javax.swing.JButton();
        areaTransf = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        painelCentMat1 = new br.com.antoniodiego.gertarefas.view.principal.PainelCentMat();
        barraDeMenus = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuExportarComoXML = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        sepMenuEd = new javax.swing.JPopupMenu.Separator();
        menuOp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPaneLadoEsq.addTab("tab1", painelListaTarefas1);

        getContentPane().add(tabPaneLadoEsq, java.awt.BorderLayout.LINE_START);

        tabPaneLadoDir.setPreferredSize(new java.awt.Dimension(200, 600));
        tabPaneLadoDir.addTab("tab1", painelFuncoes1);
        tabPaneLadoDir.addTab("tab2", painelAgendamentosMat1);
        tabPaneLadoDir.addTab("tab3", painelNotificacoesM1);

        getContentPane().add(tabPaneLadoDir, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
        painelInferior.setLayout(painelInferiorLayout);
        painelInferiorLayout.setHorizontalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelInferiorLayout.setVerticalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(painelInferior, java.awt.BorderLayout.PAGE_END);

        painelBarraFerra.setPreferredSize(new java.awt.Dimension(100, 35));

        gruposETarefa.setRollover(true);
        gruposETarefa.setToolTipText("");

        jButton1.setText("Nova tarefa");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gruposETarefa.add(jButton1);

        jButton2.setText("Escluir tarefa");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gruposETarefa.add(jButton2);

        jButton3.setText("Novo grupo");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gruposETarefa.add(jButton3);

        jButton4.setText("Excluir grupo");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gruposETarefa.add(jButton4);

        jButton7.setText("Colar");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gruposETarefa.add(jButton7);

        exportacao.setRollover(true);

        jButton8.setText("Exportar");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exportacao.add(jButton8);

        areaTransf.setRollover(true);

        jButton6.setText("Recortar");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        areaTransf.add(jButton6);

        jButton5.setText("Copiar");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        areaTransf.add(jButton5);

        javax.swing.GroupLayout painelBarraFerraLayout = new javax.swing.GroupLayout(painelBarraFerra);
        painelBarraFerra.setLayout(painelBarraFerraLayout);
        painelBarraFerraLayout.setHorizontalGroup(
            painelBarraFerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBarraFerraLayout.createSequentialGroup()
                .addComponent(gruposETarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(areaTransf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportacao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 639, Short.MAX_VALUE))
        );
        painelBarraFerraLayout.setVerticalGroup(
            painelBarraFerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBarraFerraLayout.createSequentialGroup()
                .addGroup(painelBarraFerraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaTransf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gruposETarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(exportacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(painelBarraFerra, java.awt.BorderLayout.NORTH);

        painelCentMat1.setPreferredSize(new java.awt.Dimension(100, 400));

        javax.swing.GroupLayout painelCentMat1Layout = new javax.swing.GroupLayout(painelCentMat1);
        painelCentMat1.setLayout(painelCentMat1Layout);
        painelCentMat1Layout.setHorizontalGroup(
            painelCentMat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        painelCentMat1Layout.setVerticalGroup(
            painelCentMat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        getContentPane().add(painelCentMat1, java.awt.BorderLayout.CENTER);

        menuArquivo.setText("Arquivo");

        jMenuItem1.setText("Nova tarefa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArquivo.add(jMenuItem1);

        jMenuItem2.setText("Novo grupo");
        menuArquivo.add(jMenuItem2);

        jMenuItem3.setText("Agendar");
        menuArquivo.add(jMenuItem3);

        jMenuItem4.setText("Ver detalhes");
        menuArquivo.add(jMenuItem4);

        jMenuItem5.setText("Excluir tudo");
        menuArquivo.add(jMenuItem5);

        jMenuItem6.setText("Trocar usuário");
        menuArquivo.add(jMenuItem6);

        jMenuItem7.setText("Sair");
        menuArquivo.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        menuArquivo.add(jMenuItem8);

        jMenuItem9.setText("Excluir tarefa");
        menuArquivo.add(jMenuItem9);

        jMenuItem10.setText("Reiniciar banco");
        menuArquivo.add(jMenuItem10);

        jMenuItem11.setText("Fazer backup do banco");
        menuArquivo.add(jMenuItem11);

        jMenuItem12.setText("Exportar como texto");
        menuArquivo.add(jMenuItem12);

        menuExportarComoXML.setText("Exportar XML");
        menuExportarComoXML.setToolTipText("Exporta todas as tarefas para um arquivo XML");
        menuExportarComoXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExportarComoXMLActionPerformed(evt);
            }
        });
        menuArquivo.add(menuExportarComoXML);

        jMenuItem14.setText("Importar de XML");
        menuArquivo.add(jMenuItem14);

        jMenuItem15.setText("jMenuItem15");
        menuArquivo.add(jMenuItem15);

        barraDeMenus.add(menuArquivo);

        menuEditar.setText("Editar");
        menuEditar.add(sepMenuEd);

        menuOp.setText("Opções");
        menuEditar.add(menuOp);

        barraDeMenus.add(menuEditar);

        jMenu3.setText("Exibir");
        barraDeMenus.add(jMenu3);

        jMenu4.setText("Ajuda");
        barraDeMenus.add(jMenu4);

        setJMenuBar(barraDeMenus);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuExportarComoXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExportarComoXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExportarComoXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalMatisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalMatisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalMatisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipalMatisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipalMatisse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar areaTransf;
    private javax.swing.JMenuBar barraDeMenus;
    private javax.swing.JToolBar exportacao;
    private javax.swing.JToolBar gruposETarefa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuExportarComoXML;
    private javax.swing.JMenuItem menuOp;
    private br.com.antoniodiego.gertarefas.view.principal.PainelAgendamentosMat painelAgendamentosMat1;
    private javax.swing.JPanel painelBarraFerra;
    private br.com.antoniodiego.gertarefas.view.principal.PainelCentMat painelCentMat1;
    private br.com.antoniodiego.gertarefas.view.principal.PainelFuncoes painelFuncoes1;
    private javax.swing.JPanel painelInferior;
    private br.com.antoniodiego.gertarefas.view.principal.PainelListaTarefas painelListaTarefas1;
    private br.com.antoniodiego.gertarefas.view.principal.PainelNotificacoesM painelNotificacoesM1;
    private javax.swing.JPopupMenu.Separator sepMenuEd;
    private javax.swing.JTabbedPane tabPaneLadoDir;
    private javax.swing.JTabbedPane tabPaneLadoEsq;
    // End of variables declaration//GEN-END:variables
}
