/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.antoniodiego.gertarefas.telas.detalhes;

import br.com.antoniodiego.gertarefas.persist.daos.DAOTarefa;
import br.com.antoniodiego.gertarefas.pojo.Tarefa;
import java.awt.Dialog;
import java.time.LocalDateTime;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Document;

/**
 *
 * @author Antonio Diêgo
 */
public class FrameDetalhes extends javax.swing.JFrame implements DocumentListener {

    private Tarefa t;

    /**
     * Creates new form FrameDetalhes
     */
    public FrameDetalhes() {
        initComponents();

        iconeConc = new ImageIcon(this.getClass().getResource("/imagens/icone_concluida.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDetalhes = new javax.swing.JTextPane();
        btSalvarAlteracoes = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        rotTarefa = new javax.swing.JLabel();
        rotTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTitulo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar comentário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Comentário");

        campoDetalhes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(campoDetalhes);

        btSalvarAlteracoes.setText("Salvar alterações");
        btSalvarAlteracoes.setEnabled(false);
        btSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAlteracoesActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        rotTarefa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotTarefa.setText("Tarefa:");

        campoTitulo.setEditable(false);
        campoTitulo.setColumns(2);
        campoTitulo.setLineWrap(true);
        campoTitulo.setRows(5);
        jScrollPane2.setViewportView(campoTitulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rotTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rotTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 434, Short.MAX_VALUE)
                                .addComponent(btSalvarAlteracoes)
                                .addGap(18, 18, 18)
                                .addComponent(btFechar)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotTarefa)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotTitulo)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarAlteracoes)
                    .addComponent(btFechar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ImageIcon iconeConc;
    Timer timer = new Timer();

    private void btSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAlteracoesActionPerformed
        try {
            String texto = documento.getText(0, documento.getLength());

            t.setComentario(texto);
            t.setDataModif(LocalDateTime.now());

            DAOTarefa daoT = new DAOTarefa();
            daoT.atualiza(t);

            alteracoes = false;

            btSalvarAlteracoes.setEnabled(false);

            JOptionPane op = new JOptionPane("Comentário alterado",
                    JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, iconeConc);
            Dialog d = op.createDialog(this, "Sucesso");
            d.setModal(false);
            
            d.setVisible(true);

            System.out.println("exibiu di");
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    System.out.println("rodando tarefa");
                  // d.setVisible(false);
                   d.dispose();
                }
            }, 2000);
            
         
        } catch (BadLocationException ex) {
            Logger.getLogger(FrameDetalhes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarAlteracoesActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("closing...");
        if (alteracoes) {
            int res = JOptionPane.showConfirmDialog(this, "Salvar alterações ?");
            switch (res) {
                case JOptionPane.OK_OPTION:
                    btSalvarAlteracoesActionPerformed(null);
                    this.dispose();
                    break;
                case JOptionPane.NO_OPTION:
                    this.dispose();
                    break;
                case JOptionPane.CANCEL_OPTION:
                    break;
                default:
                    throw new AssertionError();
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private Document documento;

    public void setTarefa(Tarefa t) {
        documento = new DefaultStyledDocument();

        try {
            documento.insertString(0, t.getComentario(), null);
        } catch (BadLocationException ex) {
            Logger.getLogger(FrameDetalhes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         documento.addDocumentListener(this);

        campoDetalhes.setDocument(documento);

        campoDetalhes.setCaretPosition(documento.getLength());

        this.t = t;

        campoTitulo.setText(t.getTitulo());
        
        btSalvarAlteracoes.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btSalvarAlteracoes;
    private javax.swing.JTextPane campoDetalhes;
    private javax.swing.JTextArea campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rotTarefa;
    private javax.swing.JLabel rotTitulo;
    // End of variables declaration//GEN-END:variables

    boolean alteracoes = false;

    @Override
    public void insertUpdate(DocumentEvent e) {
        alteracoes = true;
        btSalvarAlteracoes.setEnabled(true);
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        alteracoes = true;
        btSalvarAlteracoes.setEnabled(true);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        alteracoes = true;
        btSalvarAlteracoes.setEnabled(true);
    }
}
