/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.antoniodiego.gertarefas.telas;

import br.com.antoniodiego.gertarefas.beans.BeanDatePick;
import static br.com.antoniodiego.gertarefas.controller.DialogoNovaTarefaController.logDNT;
import br.com.antoniodiego.gertarefas.model.ModeloTabelaTarefasLista;
import br.com.antoniodiego.gertarefas.persist.daos.DAOTarefa;
import br.com.antoniodiego.gertarefas.pojo.TarefaComposta;
import br.com.antoniodiego.gertarefas.util.FuncoesTarefas;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Antônoio Diego <antoniodiegoluz at gmail.com>
 */
public class DialogoNovaTarView extends javax.swing.JDialog {

    private final ModeloTabelaTarefasLista modelo;
    // private final DialogoNovaTarefaController contro;
    private final JFrame princ;
    private final SpinnerNumberModel modeloSpinnerPosicao;

    /**
     * Creates new form DialogoNovaTarView
     * @param princ
     * @param modelTab
     */
    public DialogoNovaTarView(JFrame princ, ModeloTabelaTarefasLista modelTab) {
        super(princ, "Nova tarefa", false);
        this.modelo = modelTab;
        this.princ = princ;
        initComponents();
        // contro = new DialogoNovaTarefaController(this);
        modeloSpinnerPosicao = new SpinnerNumberModel(0, 0, 2000, 1);
        spinnerPosicao.setModel(modeloSpinnerPosicao);
        getRootPane().setDefaultButton(btSalvar);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDataFazer = new javax.swing.ButtonGroup();
        beanDatePick1 = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        canpoTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDEsc = new javax.swing.JTable();
        botAdic = new javax.swing.JButton();
        bRem = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoId = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btDig = new javax.swing.JRadioButton();
        campoDataFaz = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        rbEscolh = new javax.swing.JRadioButton();
        comboDataFaz = new javax.swing.JComboBox<>();
        rotuloPriori = new javax.swing.JLabel();
        campoPrioridade = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        campoDataAl = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        campoHoraAl = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        spinnerPosicao = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova tarefa");
        setLocationByPlatform(true);

        tabelaDEsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaDEsc);

        botAdic.setText("Adicionar");

        bRem.setText("Remover");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Título(opc):");

        jLabel2.setText("ID:");

        jPanel2.setLayout(new java.awt.GridLayout(6, 3, 0, 2));

        jLabel1.setText("Data para fazer:");
        jPanel2.add(jLabel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);

        btDig.setText("Digitar");
        jPanel2.add(btDig);
        jPanel2.add(campoDataFaz);

        rbEscolh.setText("Escolher");
        jPanel2.add(rbEscolh);

        comboDataFaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoje", "Amanhã", "Depois de amanhã" }));
        jPanel2.add(comboDataFaz);

        rotuloPriori.setText("Prioridade:");
        jPanel2.add(rotuloPriori);
        jPanel2.add(campoPrioridade);

        jLabel5.setText("Instante alarme:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 193, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        campoHoraAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(campoDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campoDataAl, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jLabel3.setText("Posição");
        jPanel2.add(jLabel3);
        jPanel2.add(spinnerPosicao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canpoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaoCancelar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botAdic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bRem)))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canpoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botAdic)
                            .addComponent(bRem))
                        .addGap(117, 117, 117)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalvar)
                            .addComponent(botaoCancelar))
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        logDNT.trace("Salvando tarefa...");

        //Ao criar nova
        //Obtem uma instância da tarefa
        TarefaComposta novaTarefa = new TarefaComposta();
        String tit = canpoTitulo.getText();
        novaTarefa.setTitulo(tit);
        //obs: redund
        novaTarefa.setDataCriacao(LocalDate.now());

        //  novaTarefa.setPrioridade(modeloCampoPro.getNumber().intValue());
        String idStr = campoId.getText();

        for (int i = 0; i < idStr.length(); i++) {
            if (!Character.isDigit(idStr.charAt(i))) {
                JOptionPane.showMessageDialog(this, "Id inválido", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (idStr.isEmpty()) {
            idStr = "0";
        }

        Long idNum = Long.parseLong(idStr);

        DAOTarefa daoT = new DAOTarefa();

        if (daoT.getByIdPers(idNum) != null) {
            Long maiorIdPers = daoT.getMaiorIDPers();
            novaTarefa.setIdPers(maiorIdPers + 1);
        } else {
            novaTarefa.setIdPers(idNum);
        }

        /*
        Configuração da posição
         */
        novaTarefa.setPosicao(modeloSpinnerPosicao.getNumber().intValue());

        //Fazer desvio de tarefas para baixo partindo da posição 0
        FuncoesTarefas.deslocaTarefasBaixo(0);

        /**
         * Se a operação de salvamento falhar as tarefas vão ficar deslocadas para baixo sem sobrar uma na pos 0. Talvez
         * se fosse possível tornar as duas operações em atômica seria bom, ou então desfazer o desvio das tarefas em
         * caso de falha da persistência da nova
         *
         * Deve ser bom medir a duração do processo de desvio
         */
//        Integer maiorP = daoT.getMaiorPosicao();
//        novaTarefa.setPosicao(maiorP + 1);
        daoT.salva(novaTarefa);

        dispose();

        /*
        Nesse ponto deve ser bom fazer ajustes na tabela da janela principal para ficar de acordo com novo estado
        A nova tarefa criada deve ser selecionada
        As posições devem ser atualizadas
        
        Para os valores da posição serem atualizados as tarefas deve ser buscadas novamente no banco. Talvez usar
        a paginação seria bom para diminuir a carga de trabalho
        
        */
        
        
        logDNT.trace("Adic tar na janela principal");

        modelo.recarregaTarefasBanco();

        logDNT.trace("Após adic tar na janela principal");
    }//GEN-LAST:event_btSalvarActionPerformed

    private void campoHoraAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHoraAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHoraAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoNovaTarView dialog = new DialogoNovaTarView(null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JFormattedTextField getCampoId() {
        return campoId;
    }
//
//    public DialogoNovaTarefaController getContro() {
//        return contro;
//    }

    public JButton getbRem() {
        return bRem;
    }

    public JButton getBotAdic() {
        return botAdic;
    }

    public JButton getBotaoCancelar() {
        return botaoCancelar;
    }

    public JButton getBotaoConcluido() {
        return btSalvar;
    }

    public JRadioButton getBtDig() {
        return btDig;
    }

    public BeanDatePick getCampoDataAl() {
        return campoDataAl;
    }

    public BeanDatePick getCampoDataFazer() {
        return campoDataFaz;
    }

    public JSpinner getCampoPrioridade() {
        return campoPrioridade;
    }

    public JTextField getCampoTitulo() {
        return canpoTitulo;
    }

    public JComboBox<String> getComboDataFaz() {
        return comboDataFaz;
    }

    public ButtonGroup getGrupoDataFazer() {
        return grupoDataFazer;
    }

    public JRadioButton getRbEscolh() {
        return rbEscolh;
    }

    public JLabel getRotuloPriori() {
        return rotuloPriori;
    }

    public JTable getTabelaDesc() {
        return tabelaDEsc;
    }

    public JFormattedTextField getCampoHoraAl() {
        return campoHoraAl;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRem;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick beanDatePick1;
    private javax.swing.JButton botAdic;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JRadioButton btDig;
    private javax.swing.JButton btSalvar;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataAl;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataFaz;
    private javax.swing.JFormattedTextField campoHoraAl;
    private javax.swing.JFormattedTextField campoId;
    private javax.swing.JSpinner campoPrioridade;
    private javax.swing.JTextField canpoTitulo;
    private javax.swing.JComboBox<String> comboDataFaz;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.ButtonGroup grupoDataFazer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbEscolh;
    private javax.swing.JLabel rotuloPriori;
    private javax.swing.JSpinner spinnerPosicao;
    private javax.swing.JTable tabelaDEsc;
    // End of variables declaration//GEN-END:variables
}
