
package br.com.antoniodiego.gertarefas.telas.principal;

import br.com.antoniodiego.gertarefas.beans.BeanDatePick;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Antônio Diego <antoniodiegoluz at gmail.com>
 */
public class PainelListaTarefas extends javax.swing.JPanel {

    /**
     * Creates new form PainelListaTarefas2
     */
    public PainelListaTarefas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDataAgFiltr = new javax.swing.ButtonGroup();
        painelFiltrar = new javax.swing.JPanel();
        checkDataAgend = new javax.swing.JCheckBox();
        rbHoje = new javax.swing.JRadioButton();
        rbFiltroAma = new javax.swing.JRadioButton();
        rbDataEsp = new javax.swing.JRadioButton();
        checkApenasVencidas = new javax.swing.JCheckBox();
        btFiltrar = new javax.swing.JButton();
        campoDataAgFil = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        painelDeAcoes = new javax.swing.JPanel();
        btVerDetalhes = new javax.swing.JButton();
        painelDeBusca = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        campoTextoBusca = new javax.swing.JTextField();
        scrollPaneTabela = new javax.swing.JScrollPane();
        tabelaTarefas = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(500, 65534));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        painelFiltrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        checkDataAgend.setText("Data agendamento");

        grupoDataAgFiltr.add(rbHoje);
        rbHoje.setSelected(true);
        rbHoje.setText("Hoje");

        grupoDataAgFiltr.add(rbFiltroAma);
        rbFiltroAma.setText("Amanhã");

        grupoDataAgFiltr.add(rbDataEsp);
        rbDataEsp.setText("Data esp:");

        checkApenasVencidas.setText("Apenas vencidas");

        btFiltrar.setText("Filtrar");

        javax.swing.GroupLayout painelFiltrarLayout = new javax.swing.GroupLayout(painelFiltrar);
        painelFiltrar.setLayout(painelFiltrarLayout);
        painelFiltrarLayout.setHorizontalGroup(
            painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFiltrarLayout.createSequentialGroup()
                        .addComponent(rbHoje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFiltroAma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDataEsp)
                        .addGap(18, 18, 18)
                        .addComponent(campoDataAgFil, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(painelFiltrarLayout.createSequentialGroup()
                        .addGroup(painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDataAgend)
                            .addComponent(checkApenasVencidas)
                            .addComponent(btFiltrar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelFiltrarLayout.setVerticalGroup(
            painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkDataAgend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbHoje)
                        .addComponent(rbFiltroAma)
                        .addComponent(rbDataEsp))
                    .addComponent(campoDataAgFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkApenasVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFiltrar)
                .addContainerGap())
        );

        add(painelFiltrar);

        btVerDetalhes.setText("Detalhes");
        btVerDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerDetalhesActionPerformed(evt);
            }
        });

        painelDeBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        btBuscar.setText("Buscar");

        javax.swing.GroupLayout painelDeBuscaLayout = new javax.swing.GroupLayout(painelDeBusca);
        painelDeBusca.setLayout(painelDeBuscaLayout);
        painelDeBuscaLayout.setHorizontalGroup(
            painelDeBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoTextoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btBuscar)
                .addGap(24, 24, 24))
        );
        painelDeBuscaLayout.setVerticalGroup(
            painelDeBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(campoTextoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelDeAcoesLayout = new javax.swing.GroupLayout(painelDeAcoes);
        painelDeAcoes.setLayout(painelDeAcoesLayout);
        painelDeAcoesLayout.setHorizontalGroup(
            painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeAcoesLayout.createSequentialGroup()
                        .addComponent(btVerDetalhes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelDeBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDeAcoesLayout.setVerticalGroup(
            painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVerDetalhes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(painelDeAcoes);

        tabelaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaTarefas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPaneTabela.setViewportView(tabelaTarefas);

        add(scrollPaneTabela);
    }// </editor-fold>//GEN-END:initComponents

    private void btVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVerDetalhesActionPerformed

    public JCheckBox getCheckDataAgend() {
        return checkDataAgend;
    }

    public JRadioButton getRbDataEsp() {
        return rbDataEsp;
    }

    public JRadioButton getRbFiltroAma() {
        return rbFiltroAma;
    }

    public JRadioButton getRbHoje() {
        return rbHoje;
    }

    public JTable getTabelaTarefas() {
        return tabelaTarefas;
    }

    public ButtonGroup getGrupoDataAgFiltr() {
        return grupoDataAgFiltr;
    }

    public BeanDatePick getCampoDataAgFil() {
        return campoDataAgFil;
    }

    public JCheckBox getCheckApenasVencidas() {
        return checkApenasVencidas;
    }

    public JButton getBtFiltrar() {
        return btFiltrar;
    }

    public JButton getBtBuscar() {
        return btBuscar;
    }

    public void setBtBuscar(JButton btBuscar) {
        this.btBuscar = btBuscar;
    }

    public JButton getBtVerDetalhes() {
        return btVerDetalhes;
    }

    public void setBtVerDetalhes(JButton btVerDetalhes) {
        this.btVerDetalhes = btVerDetalhes;
    }

    public JTextField getCampoTextoBusca() {
        return campoTextoBusca;
    }

    public void setCampoTextoBusca(JTextField campoTextoBusca) {
        this.campoTextoBusca = campoTextoBusca;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btVerDetalhes;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataAgFil;
    private javax.swing.JTextField campoTextoBusca;
    private javax.swing.JCheckBox checkApenasVencidas;
    private javax.swing.JCheckBox checkDataAgend;
    private javax.swing.ButtonGroup grupoDataAgFiltr;
    private javax.swing.JPanel painelDeAcoes;
    private javax.swing.JPanel painelDeBusca;
    private javax.swing.JPanel painelFiltrar;
    private javax.swing.JRadioButton rbDataEsp;
    private javax.swing.JRadioButton rbFiltroAma;
    private javax.swing.JRadioButton rbHoje;
    private javax.swing.JScrollPane scrollPaneTabela;
    private javax.swing.JTable tabelaTarefas;
    // End of variables declaration//GEN-END:variables
}
