/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.antoniodiego.gertarefas.telas.agendamentos;

import br.com.antoniodiego.gertarefas.pojo.Tarefa;
import br.com.antoniodiego.gertarefas.telas.principal.JanelaPrincipal;
import br.com.antoniodiego.gertarefas.beans.BeanDatePick;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JRadioButton;

/**
 *
 * @author Antônoio Diego <antoniodiegoluz at gmail.com>
 */
public class DialogoAgend extends javax.swing.JDialog {

    private DialogoAgendControl control;
    private Tarefa tar;

    /**
     * Creates new form DialogoAgend
     *
     * @param princ
     */
    public DialogoAgend(JanelaPrincipal princ, Tarefa tar) {
        initComponents();
        this.tar = tar;
        control = new DialogoAgendControl(this, princ.getControl());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDataAg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        campoTarefa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbHoje = new javax.swing.JRadioButton();
        rbAmanha = new javax.swing.JRadioButton();
        rbDataEsp = new javax.swing.JRadioButton();
        campoDataEsp = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        checkHora = new javax.swing.JCheckBox();
        campoHora = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendar");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Tarefa:");

        campoTarefa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Agendar para:");

        grupoDataAg.add(rbHoje);
        rbHoje.setSelected(true);
        rbHoje.setText("Hoje");

        grupoDataAg.add(rbAmanha);
        rbAmanha.setText("Amanhã");
        rbAmanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmanhaActionPerformed(evt);
            }
        });

        grupoDataAg.add(rbDataEsp);
        rbDataEsp.setText("Data esp:");

        btSalvar.setBackground(new java.awt.Color(0, 153, 102));
        btSalvar.setText("Salvar");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        checkHora.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(campoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkHora)
                                .addGap(18, 18, 18)
                                .addComponent(campoHora))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHoje)
                                .addGap(18, 18, 18)
                                .addComponent(rbAmanha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDataEsp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoDataEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHoje)
                            .addComponent(rbAmanha)
                            .addComponent(rbDataEsp))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkHora)
                    .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbAmanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmanhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAmanhaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    public Tarefa getTar() {
        return tar;
    }

    public DialogoAgendControl getControl() {
        return control;
    }

    public JButton getBtCancelar() {
        return btCancelar;
    }

    public JButton getBtSalvar() {
        return btSalvar;
    }

    public BeanDatePick getCampoDataEsp() {
        return campoDataEsp;
    }

    public JFormattedTextField getCampoHora() {
        return campoHora;
    }

    public JComboBox<String> getCampoTarefa() {
        return campoTarefa;
    }

    public JCheckBox getCheckHora() {
        return checkHora;
    }

    public JRadioButton getRbAmanha() {
        return rbAmanha;
    }

    public JRadioButton getRbDataEsp() {
        return rbDataEsp;
    }

    public JRadioButton getRbHoje() {
        return rbHoje;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataEsp;
    private javax.swing.JFormattedTextField campoHora;
    private javax.swing.JComboBox<String> campoTarefa;
    private javax.swing.JCheckBox checkHora;
    private javax.swing.ButtonGroup grupoDataAg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAmanha;
    private javax.swing.JRadioButton rbDataEsp;
    private javax.swing.JRadioButton rbHoje;
    // End of variables declaration//GEN-END:variables
}
