/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.antoniodiego.gertarefas.telas.vercomentarios;

import br.com.antoniodiego.gertarefas.pojo.Comentario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Scrollable;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Usa a mesma lista de comentários da tarefa
 *
 * @author anton
 */
public class PainelComentarios extends javax.swing.JPanel implements Scrollable, MouseMotionListener {

    private List<Comentario> coment;
    private final List<ComponenteComentario> subComponentes;
    public static final Logger LOG_C_RENDERER = LogManager.
            getLogger("painel_c");

    /**
     * Creates new form PainelComentarios
     *
     */
    public PainelComentarios() {
        initComponents();

        subComponentes = new ArrayList<>();
        this.coment = new ArrayList<>();
        //  setSize(getWidth(), 500);

        //     addMouseListener(new Adap());
        // addMouseMotionListener(this);
    }

    /**
     *  * Usa a mesma lista de comentários da tarefa
     *
     * @param coment
     */
    public void setComent(List<Comentario> coment) {
        LOG_C_RENDERER.debug("Set c");

        LOG_C_RENDERER.debug("W: " + getWidth());

        //TODO: Usar a mesma lista da tarefa
        //   this.coment.clear();
        //    this.coment.addAll(coment);
        this.coment = coment;
        Collections.sort(coment);

        int altura = 10;

        // coment = coment.subList(0, 3);
         ComponenteComentario cc;
        for (Comentario c : coment) {
           cc = new ComponenteComentario(0, c);
            cc.setaAltura(getWidth());
            //   subComponentes.add(cc);

            altura += cc.getHeight() + 10;
        }

        this.setPreferredSize(new Dimension(getWidth(), altura));
        LOG_C_RENDERER.debug("Altura painel: " + altura);

        revalidate();
        repaint();

        this.scrollRectToVisible(new Rectangle(0, altura + 50, getWidth(), 50));
    }

    public void add(Comentario c) {
        LOG_C_RENDERER.traceEntry();

        //  if (!coment.contains(c)) {
        //   this.coment.add(c);
        //    }
        LOG_C_RENDERER.debug("Total coment: " + coment.size());

        Collections.sort(coment);

        ComponenteComentario cc = new ComponenteComentario(0, c);
        cc.setaAltura(getWidth());
        //  subComponentes.add(cc);

        this.setPreferredSize(new Dimension(getWidth(), getHeight()
                + cc.getHeight() + 10));
        //System.out.println("Altura painel: " + altura);

        cc.setLocation(0, getHeight()
                + cc.getHeight() + 10 + 50);

        revalidate();
        repaint();

        this.scrollRectToVisible(cc.getBounds());
    }

    @Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(x, y, width, height);
        LOG_C_RENDERER.debug("S b painel , larg {}: ", width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        LOG_C_RENDERER.debug("Largura pc: " + getWidth());

        System.out.println("Desen " + coment.size() + " comentários");
//        g.setColor(Color.GREEN);
//        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);
        int yC = 10;
        Graphics gC;
        for (Comentario com : coment) {
            ComponenteComentario c = new ComponenteComentario(0, com);
            System.out.println("Des : " + c + " pos y " + yC);
            c.setaAltura(getWidth());
            c.setBounds(0, yC, getWidth(), c.getHeight());
            gC = g.create(0, yC, c.getWidth(), c.getHeight());
            c.paint(gC);
            yC += c.getHeight() + 10;
        }
    }

    @Override
    public Dimension getPreferredScrollableViewportSize() {
        return new Dimension(400, getHeight());
    }

    @Override
    public int getScrollableUnitIncrement(Rectangle visibleRect, int orientation, int direction) {
        return 50;
    }

    @Override
    public int getScrollableBlockIncrement(Rectangle visibleRect, int orientation, int direction) {
        return 50;
    }

    @Override
    public boolean getScrollableTracksViewportWidth() {
        return true;
    }

    @Override
    public boolean getScrollableTracksViewportHeight() {
        return false;
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        System.out.println("mouse dra list: " + e.getPoint());
        Rectangle c = new Rectangle(e.getPoint(), new Dimension(1, 1));
        scrollRectToVisible(c);
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        System.out.println("mouse mov list: " + e.getPoint());
        Rectangle c = new Rectangle(e.getPoint(), new Dimension(1, 1));
        scrollRectToVisible(c);
    }

    private class Adap extends MouseAdapter {

        @Override
        public void mouseMoved(MouseEvent e) {
            System.out.println("mouse mov ad");
            Rectangle c = new Rectangle(e.getPoint(), new Dimension(1, 1));
            scrollRectToVisible(c);
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            System.out.println("mouse dra ad");
            Rectangle c = new Rectangle(e.getPoint(), new Dimension(1, 1));
            scrollRectToVisible(c);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
