/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.antoniodiego.gertarefas.telas.vercomentarios;

import br.com.antoniodiego.gertarefas.pojo.Comentario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Scrollable;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author anton
 */
public class PainelComentarios extends javax.swing.JPanel implements Scrollable {

    private List<Comentario> coment;
    private final List<ComponenteComentario> subComponentes;
    public static final Logger LOG_C_RENDERER = LogManager.
            getLogger("painel_c");

    /**
     * Creates new form PainelComentarios
     *
     */
    public PainelComentarios() {
        initComponents();

        subComponentes = new ArrayList<>();

        //  setSize(getWidth(), 500);
    }

    public void setComent(List<Comentario> coment) {
        LOG_C_RENDERER.debug("Set c");

        LOG_C_RENDERER.debug("W: " + getWidth());

        this.coment = coment;
        Collections.sort(coment);

        int altura = 10;

        // coment = coment.subList(0, 3);
        for (Comentario c : coment) {
            ComponenteComentario cc = new ComponenteComentario(0, c);
            cc.setaAltura(getWidth());
            //   subComponentes.add(cc);

            altura += cc.getHeight() + 10;
        }

        this.setPreferredSize(new Dimension(getWidth(), altura));
        System.out.println("Altura painel: " + altura);
        revalidate();
        repaint();
    }

    public void add(Comentario c) {
        this.coment.add(c);

        Collections.sort(coment);

        ComponenteComentario cc = new ComponenteComentario(0, c);
        cc.setaAltura(getWidth());
        //  subComponentes.add(cc);

        this.setPreferredSize(new Dimension(getWidth(), getHeight()
                + cc.getHeight() + 10));
        //System.out.println("Altura painel: " + altura);
        revalidate();
        repaint();
    }

    @Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(x, y, width, height);
        LOG_C_RENDERER.debug("S b painel , larg {}: ", width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        LOG_C_RENDERER.debug("Largura pc: " + getWidth());

//        g.setColor(Color.GREEN);
//        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);
        int yC = 10;
        Graphics gC;
        for (Comentario com : coment) {
            ComponenteComentario c = new ComponenteComentario(0, com);
            System.out.println("Des : " + c);
            c.setaAltura(getWidth());
            c.setBounds(0, yC, getWidth(), c.getHeight());
            gC = g.create(0, yC, c.getWidth(), c.getHeight());
            c.paint(gC);
            yC += c.getHeight() + 10;
        }
    }

    @Override
    public Dimension getPreferredScrollableViewportSize() {
        return new Dimension(400, getHeight());
    }

    @Override
    public int getScrollableUnitIncrement(Rectangle visibleRect, int orientation, int direction) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public int getScrollableBlockIncrement(Rectangle visibleRect, int orientation, int direction) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean getScrollableTracksViewportWidth() {
        return true;
    }

    @Override
    public boolean getScrollableTracksViewportHeight() {
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
