/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.antoniodiego.gertarefas.telas.vercomentarios;

import br.com.antoniodiego.gertarefas.pojo.Comentario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author anton
 */
public class PainelComentarios extends javax.swing.JPanel {

    private List<Comentario> coment;
    private List<ComponenteComentario> subComponentes;
    public static final Logger LOG_C_RENDERER = LogManager.
            getLogger("painel_c");

    /**
     * Creates new form PainelComentarios
     *
     */
    public PainelComentarios() {
        initComponents();

        subComponentes = new ArrayList<>();

        //  setSize(getWidth(), 500);
    }

    public void setComent(List<Comentario> coment) {
        LOG_C_RENDERER.debug("Set c");

        this.coment = coment;

        int altura = 10;

        Comentario c = coment.get(0);
     //   for (Comentario c : coment) {
            ComponenteComentario cc = new ComponenteComentario(0, c);
            cc.setaAltura(getWidth());
            subComponentes.add(cc);

            altura += cc.getHeight();
       // }

        this.setPreferredSize(new Dimension(getWidth(), altura));
        System.out.println("Altura painel: " + altura);
        revalidate();
    }

    public void add(Comentario c) {
        ComponenteComentario cc = new ComponenteComentario(0, c);
        subComponentes.add(cc);

        this.setPreferredSize(new Dimension(getWidth(), getHeight() + cc.getHeight()));
        //System.out.println("Altura painel: " + altura);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        g.setColor(Color.GREEN);
        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);

        int yC = 10;
        Graphics gC;
        for (ComponenteComentario c : subComponentes) {
            System.out.println("Des : " + c);
            c.setaAltura(getWidth());
            c.setBounds(0, yC, getWidth(), c.getHeight());
            gC = g.create(0, yC, c.getWidth(), c.getHeight());
            c.paint(gC);
            yC = +c.getHeight() + 10;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
