/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.antoniodiego.gertarefas.telas.novatarefa;

import java.io.IOException;
import java.time.LocalDate;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import br.com.antoniodiego.gertarefas.beans.BeanDatePick;
import br.com.antoniodiego.gertarefas.logging.LoggingParaArquivo;
import br.com.antoniodiego.gertarefas.model.ModeloTabelaTarefasLista;
import br.com.antoniodiego.gertarefas.persist.daos.DAOTarefa;
import br.com.antoniodiego.gertarefas.pojo.TarefaComposta;
import br.com.antoniodiego.gertarefas.util.FuncoesTarefas;

/**
 *
 * @author Antônoio Diego <antoniodiegoluz at gmail.com>
 */
public class DialogoNovaTarView extends javax.swing.JDialog {

    /**
    *
    */
    public static final Logger LOG_ARQUIVO = LogManager.getLogger("saida_para_arquivo");

    /**
     *
     */
    public static final Logger LOG_NOVA_TAREFA = LogManager.getLogger("nova_tarefa");

    private final ModeloTabelaTarefasLista modelo;
    private final SpinnerNumberModel modeloSpinnerPosicao;

    /**
     * Creates new form DialogoNovaTarView
     * 
     * @param princ
     * @param modelTab
     */
    public DialogoNovaTarView(JFrame princ, ModeloTabelaTarefasLista modelTab) {
        super(princ, "Nova tarefa", false);
        this.modelo = modelTab;

        initComponents();
        // contro = new DialogoNovaTarefaController(this);
        modeloSpinnerPosicao = new SpinnerNumberModel(0, 0, 2000, 1);
        spinnerPosicao.setModel(modeloSpinnerPosicao);
        getRootPane().setDefaultButton(btSalvar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDataFazer = new javax.swing.ButtonGroup();
        beanDatePick1 = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        canpoTitulo = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        painelSubTarefas = new javax.swing.JPanel();
        bRem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDEsc = new javax.swing.JTable();
        botAdic = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        painelPrazo = new javax.swing.JPanel();
        comboDataFaz = new javax.swing.JComboBox<>();
        campoDataFaz = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        rbEscolh = new javax.swing.JRadioButton();
        btDig = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        spinnerPosicao = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        rotuloPriori = new javax.swing.JLabel();
        campoPrioridade = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        campoDataAl = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        campoHoraAl = new javax.swing.JFormattedTextField();
        campoId = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova tarefa");
        setLocationByPlatform(true);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Título(opc):");

        painelSubTarefas.setBorder(javax.swing.BorderFactory.createTitledBorder("Subtarefas"));

        bRem.setText("Remover");

        tabelaDEsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaDEsc);

        botAdic.setText("Adicionar");

        javax.swing.GroupLayout painelSubTarefasLayout = new javax.swing.GroupLayout(painelSubTarefas);
        painelSubTarefas.setLayout(painelSubTarefasLayout);
        painelSubTarefasLayout.setHorizontalGroup(
            painelSubTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSubTarefasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSubTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botAdic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bRem)
                .addGap(74, 74, 74))
        );
        painelSubTarefasLayout.setVerticalGroup(
            painelSubTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSubTarefasLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelSubTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRem)
                    .addComponent(botAdic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setText("Data para fazer:");

        comboDataFaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoje", "Amanhã", "Depois de amanhã" }));
        comboDataFaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDataFazActionPerformed(evt);
            }
        });

        campoDataFaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataFazActionPerformed(evt);
            }
        });

        grupoDataFazer.add(rbEscolh);
        rbEscolh.setSelected(true);
        rbEscolh.setText("Escolher");

        btDig.setText("Digitar");

        javax.swing.GroupLayout painelPrazoLayout = new javax.swing.GroupLayout(painelPrazo);
        painelPrazo.setLayout(painelPrazoLayout);
        painelPrazoLayout.setHorizontalGroup(
            painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrazoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEscolh, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGap(107, 107, 107)
                .addGroup(painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoDataFaz, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(comboDataFaz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrazoLayout.setVerticalGroup(
            painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrazoLayout.createSequentialGroup()
                .addGroup(painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEscolh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDataFaz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDig, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataFaz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel3.setText("Posição");

        jLabel2.setText("ID:");

        rotuloPriori.setText("Prioridade:");

        jLabel5.setText("Instante alarme:");

        jLabel6.setText("Comentário");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        campoHoraAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(45, 45, 45)
                            .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(483, 483, 483))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoCancelar)
                            .addGap(21, 21, 21)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(canpoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painelPrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotuloPriori, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(71, 71, 71)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(campoDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(campoPrioridade)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(spinnerPosicao)))
                            .addComponent(painelSubTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(canpoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloPriori, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(campoDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botaoCancelar)
                                    .addComponent(btSalvar))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelSubTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataFazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataFazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataFazActionPerformed

    private void comboDataFazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDataFazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDataFazActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_botaoCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvarActionPerformed
        LOG_NOVA_TAREFA.trace("Salvando tarefa...");

        // Ao criar nova
        // Obtem uma instância da tarefa
        TarefaComposta novaTarefa = new TarefaComposta();
        String tit = canpoTitulo.getText();
        novaTarefa.setTitulo(tit);
        // obs: redund
        novaTarefa.setDataCriacao(LocalDate.now());

        // novaTarefa.setPrioridade(modeloCampoPro.getNumber().intValue());
        String idStr = campoId.getText();

        for (int i = 0; i < idStr.length(); i++) {
            if (!Character.isDigit(idStr.charAt(i))) {
                JOptionPane.showMessageDialog(this, "Id inválido", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (idStr.isEmpty()) {
            idStr = "0";
        }

        Long idNum = Long.parseLong(idStr);

        DAOTarefa daoT = new DAOTarefa();

        if (daoT.getByIdPers(idNum) != null) {
            Long maiorIdPers = daoT.getMaiorIDPers();
            novaTarefa.setIdPers(maiorIdPers + 1);
        } else {
            novaTarefa.setIdPers(idNum);
        }

        /*
         * Configuração da posição
         */
        novaTarefa.setPosicao(modeloSpinnerPosicao.getNumber().intValue());

        // Fazer desvio de tarefas para baixo partindo da posição 0
        FuncoesTarefas.deslocaTarefasBaixo(0);

        /**
         * Se a operação de salvamento falhar as tarefas vão ficar deslocadas para baixo
         * sem sobrar uma na pos 0. Talvez
         * se fosse possível tornar as duas operações em atômica seria bom, ou então
         * desfazer o desvio das tarefas em
         * caso de falha da persistência da nova
         *
         * Deve ser bom medir a duração do processo de desvio
         */
        // Integer maiorP = daoT.getMaiorPosicao();
        // novaTarefa.setPosicao(maiorP + 1);
        daoT.salva(novaTarefa);

        LoggingParaArquivo loggingParaArquivo = LoggingParaArquivo.getInstancia();

        LOG_ARQUIVO.trace("[CRIADA] Foi salva a tarefa de título '{}' e id '{}'. id pers: '{}', comentário: '{}'" +
                ", posicao: '{}'", novaTarefa.getTitulo(),
                novaTarefa.getId(), novaTarefa.getIdPers(), novaTarefa.getComentario(), novaTarefa.getPosicao());

        try {
            loggingParaArquivo.loga(
                    "[CRIADA] Foi salva a tarefa de título '%s' e id '%s'. id pers: '%s', comentário: '%s'" +
                            ", posicao: '%s'",
                    novaTarefa.getTitulo(),
                    novaTarefa.getId(), novaTarefa.getIdPers(), novaTarefa.getComentario(), novaTarefa.getPosicao());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        dispose();

        /*
         * Nesse ponto deve ser bom fazer ajustes na tabela da janela principal para
         * ficar de acordo com novo estado
         * A nova tarefa criada deve ser selecionada
         * As posições devem ser atualizadas
         * 
         * Para os valores da posição serem atualizados as tarefas deve ser buscadas
         * novamente no banco. Talvez usar
         * a paginação seria bom para diminuir a carga de trabalho
         * 
         */

        LOG_NOVA_TAREFA.trace("Adic tar na janela principal");

        modelo.recarregaTarefasBanco();

        LOG_NOVA_TAREFA.trace("Após adic tar na janela principal");
    }// GEN-LAST:event_btSalvarActionPerformed

    private void campoHoraAlActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoHoraAlActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoHoraAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoNovaTarView.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoNovaTarView dialog = new DialogoNovaTarView(null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JFormattedTextField getCampoId() {
        return campoId;
    }
    //
    // public DialogoNovaTarefaController getContro() {
    // return contro;
    // }

    public JButton getbRem() {
        return bRem;
    }

    public JButton getBotAdic() {
        return botAdic;
    }

    public JButton getBotaoCancelar() {
        return botaoCancelar;
    }

    public JButton getBotaoConcluido() {
        return btSalvar;
    }

    public JRadioButton getBtDig() {
        return btDig;
    }

    public BeanDatePick getCampoDataAl() {
        return campoDataAl;
    }

    public BeanDatePick getCampoDataFazer() {
        return campoDataFaz;
    }

    public JSpinner getCampoPrioridade() {
        return campoPrioridade;
    }

    public JTextField getCampoTitulo() {
        return canpoTitulo;
    }

    public JComboBox<String> getComboDataFaz() {
        return comboDataFaz;
    }

    public ButtonGroup getGrupoDataFazer() {
        return grupoDataFazer;
    }

    public JRadioButton getRbEscolh() {
        return rbEscolh;
    }

    public JLabel getRotuloPriori() {
        return rotuloPriori;
    }

    public JTable getTabelaDesc() {
        return tabelaDEsc;
    }

    public JFormattedTextField getCampoHoraAl() {
        return campoHoraAl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRem;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick beanDatePick1;
    private javax.swing.JButton botAdic;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JRadioButton btDig;
    private javax.swing.JButton btSalvar;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataAl;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataFaz;
    private javax.swing.JFormattedTextField campoHoraAl;
    private javax.swing.JFormattedTextField campoId;
    private javax.swing.JSpinner campoPrioridade;
    private javax.swing.JTextField canpoTitulo;
    private javax.swing.JComboBox<String> comboDataFaz;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.ButtonGroup grupoDataFazer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel painelPrazo;
    private javax.swing.JPanel painelSubTarefas;
    private javax.swing.JRadioButton rbEscolh;
    private javax.swing.JLabel rotuloPriori;
    private javax.swing.JSpinner spinnerPosicao;
    private javax.swing.JTable tabelaDEsc;
    // End of variables declaration//GEN-END:variables
}
