/**
 * Author:  Antônoio Diego <antoniodiegoluz at gmail.com>
 * Created: 15 de mai de 2020
 */

CREATE TABLE GRUPOTAREFAS(
ID INTEGER IDENTITY,
TITULO VARCHAR(255),
PAI_ID INTEGER,
CONSTRAINT FK6DEYU5FMJ2QM7T14PSEOOBT78 FOREIGN KEY(PAI_ID) REFERENCES GRUPOTAREFAS(ID)
);

CREATE TABLE TAREFA(
DTYPE VARCHAR(31) NOT NULL,
ID INTEGER IDENTITY,
CONCLUIDA BOOLEAN NOT NULL,
DATACONCLUSAO TIMESTAMP,
DATACRIACAO DATE,
DATAFAZER DATE,
PRIORIDADE INTEGER,
TITULO VARCHAR(255),
PAI_ID BIGINT,
CONSTRAINT FK7SGVAKJ7GTCYH2YLDBKGGPDBQ FOREIGN KEY(PAI_ID) REFERENCES GRUPOTAREFAS(ID)
);

CREATE TABLE TAREFACOMPOSTA_TAREFASFILHAS(
TAREFACOMPOSTA_ID INTEGER NOT NULL,
COMENTARIO LONGVARCHAR,
CONCLUIDA BOOLEAN NOT NULL,
DATACONCLUSAO TIMESTAMP,
DESCRICAO LONGVARCHAR,
CONSTRAINT FKD1TDSWPD2V8IF390HODV41O3F FOREIGN KEY(TAREFACOMPOSTA_ID) REFERENCES PUBLIC.TAREFA(ID)
);

CREATE TABLE USUARIO(
ID INTEGER NOT NULL IDENTITY,
EMB VARCHAR(255),
NOME VARCHAR(255),
GRUPORAIZ_ID BIGINT,
CONSTRAINT UK_FRYX2HB27TVV9B3VSW5JIK8IC UNIQUE(EMB),
CONSTRAINT UK_73L619D30RT4W3WVGNU7OQOT3 UNIQUE(NOME),
CONSTRAINT FKS4XI9RR0XDQ9RN9547U3XQ3EN FOREIGN KEY(GRUPORAIZ_ID) REFERENCES PUBLIC.GRUPOTAREFAS(ID),
CONSTRAINT UK_FL3UVB053WJKJLY059T4J7XJP UNIQUE(EMB,NOME)
);
