/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.antoniodiego.gertarefas.telas.dialogos.editartarefa;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Objects;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSpinner;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import br.com.antoniodiego.gertarefas.Constantes;
import br.com.antoniodiego.gertarefas.beans.BeanDatePick;
import br.com.antoniodiego.gertarefas.logging.LoggingParaArquivo;
import br.com.antoniodiego.gertarefas.model.ModeloTabelaTarefasLista;
import br.com.antoniodiego.gertarefas.persist.daos.DAOTarefa;
import br.com.antoniodiego.gertarefas.pojo.Tarefa;
import java.io.IOException;
import java.time.LocalDateTime;
import javax.swing.JTextArea;

/**
 *
 * @author Antônio Diego <antoniodiegoluz at gmail.com>
 */
public class DialogoEditarTarefa extends javax.swing.JDialog {

    /**
     *
     */
    public static final Logger LOG_ARQUIVO = LogManager.getLogger("saida_para_arquivo");

    /**
     *
     */
    public static final Logger LOG_EDITAR_TAREFA = LogManager.getLogger("editar_tarefa");
    private final ModeloTabelaTarefasLista modelo;

    private Tarefa tarefa;

    /**
     * Creates new form DialogoNovaTarView
     *
     * @param princ
     * @param modelTab
     */
    public DialogoEditarTarefa(JFrame princ, ModeloTabelaTarefasLista modelTab) {
        super(princ, "Nova tarefa", false);
        this.modelo = modelTab;
        initComponents();

        setLocationRelativeTo(princ);
        // contro = new DialogoNovaTarefaController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDataFazer = new javax.swing.ButtonGroup();
        beanDatePick1 = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        jLabel1 = new javax.swing.JLabel();
        rotuloPriori = new javax.swing.JLabel();
        campoPrioridade = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        botaoConcluido = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoPrazo = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        campoDataAl = new br.com.antoniodiego.gertarefas.beans.BeanDatePick();
        campoHoraAl = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        campoId = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComentários = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        campoStatus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoPosicao = new javax.swing.JComboBox<>();
        btData = new javax.swing.JButton();
        btHora = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTitulo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar tarefa");

        jLabel1.setText("Prazo:");

        rotuloPriori.setText("Prioridade:");

        jLabel3.setText("Alarme:");

        botaoConcluido.setText("Salvar");
        botaoConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluidoActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome:");

        campoPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrazoActionPerformed(evt);
            }
        });

        campoHoraAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHoraAlActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");
        jLabel2.setToolTipText("ID universal (personalizado)");

        campoId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###############"))));
        campoId.setPreferredSize(new java.awt.Dimension(5, 24));
        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });

        jLabel5.setText("Comentários:");

        campoComentários.setColumns(20);
        campoComentários.setLineWrap(true);
        campoComentários.setRows(5);
        campoComentários.setWrapStyleWord(true);
        jScrollPane1.setViewportView(campoComentários);

        jLabel6.setText("Status:");

        campoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoStatusActionPerformed(evt);
            }
        });

        jLabel7.setText("Posição:");

        btData.setText("Data");
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });

        btHora.setText("Hora");
        btHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoraActionPerformed(evt);
            }
        });

        campoTitulo.setColumns(20);
        campoTitulo.setLineWrap(true);
        campoTitulo.setRows(5);
        jScrollPane2.setViewportView(campoTitulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoConcluido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(218, 218, 218)
                        .addComponent(btData, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btHora))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(195, 195, 195)
                                        .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rotuloPriori)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoStatus)
                                            .addComponent(campoPosicao, 0, 139, Short.MAX_VALUE)
                                            .addComponent(campoPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoPrioridade, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(campoDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(campoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btData)
                        .addComponent(btHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloPriori)
                    .addComponent(campoPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoHoraAl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConcluido)
                    .addComponent(botaoCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }// GEN-LAST:event_botaoCancelarActionPerformed

    private void campoHoraAlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }// GEN-LAST:event_campoHoraAlActionPerformed

    private void botaoConcluidoActionPerformed(java.awt.event.ActionEvent evt) {
        LOG_EDITAR_TAREFA.trace("Salvando tarefa...");

        String tit = campoTitulo.getText();
        tarefa.setTitulo(tit);
        tarefa.setDataFazer(campoPrazo.getModeloDef().getValue());

        String comentarioAtual = tarefa.getComentario();
        Long idPersAtual = tarefa.getIdPers();

        tarefa.setComentario(campoComentários.getText());
        tarefa.setStatus(campoStatus.getText());
        tarefa.setDataModif(LocalDateTime.now());

        Number idCampo = (Number) campoId.getValue();

        if (idCampo == null) {
            idCampo = 0;
        }

        Long idComoNumero = idCampo.longValue();

        DAOTarefa daoTarefa = new DAOTarefa();

        Tarefa tarefaComId = daoTarefa.getByIdPers(idComoNumero);

        LOG_ARQUIVO.debug("Tarefa enc com id pers {}: {}",
                idComoNumero, tarefaComId);

        if (tarefaComId != null && !Objects.equals(tarefaComId.getId(),
                tarefa.getId())) {
            LOG_ARQUIVO.debug("Encontrou tarefa com id personalizado {} salva"
                    + " que não é tarefa atual",
                    idComoNumero);

            Long maiorIdPers = daoTarefa.getMaiorIDPers();
            tarefa.setIdPers(maiorIdPers + 1);
        } else {
            tarefa.setIdPers(idComoNumero);
        }

        daoTarefa.atualiza(tarefa);

        LoggingParaArquivo loggingParaArquivo = LoggingParaArquivo.
                getInstancia();

        try {
            loggingParaArquivo.loga(
                    "[EDIÇÃO] A tarefa %s de id %d foi editada. Novo "
                    + "comentário: '%s' ,anterior: '%s', novo id"
                    + " perso.: '%d' "
                    + ", anterior: '%d'",
                    tarefa.getTitulo(), tarefa.getId(), tarefa.getComentario(),
                    comentarioAtual, tarefa.getIdPers(),
                    idPersAtual);
        } catch (IOException e) {
            LOG_EDITAR_TAREFA.catching(e);
        }

        LOG_ARQUIVO.debug(
                "[EDIÇÃO] A tarefa {} de id {} foi editada. Novo comentário: "
                + "'{}' ,anterior: '{}', novo id perso.: '{}' "
                + ", anterior: '{}'",
                tarefa.getTitulo(), tarefa.getId(), tarefa.getComentario(),
                comentarioAtual, tarefa.getIdPers(),
                idPersAtual);

        dispose();

        LOG_EDITAR_TAREFA.trace("Adic tar na janela principal");

        modelo.ordena();

        LOG_EDITAR_TAREFA.trace("Após adic tar na janela principal");
    }// GEN-LAST:event_botaoConcluidoActionPerformed

    public void setTarefa(Tarefa t) {
        this.tarefa = t;

        campoTitulo.setText(t.getTitulo());

        LocalDate prazo = t.getDataFazer();

        if (prazo != null) {

            campoPrazo.getModeloDef().setValue(prazo);
            // prazo.getYear());
        }

        campoComentários.setText(t.getComentario());
        campoStatus.setText(t.getStatus());
        campoPosicao.setSelectedItem(t);
        campoPrioridade.setValue(t.getPrioridade());
        campoId.setValue(t.getIdPers());
    }

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
    }// GEN-LAST:event_campoIdActionPerformed

    private void campoPrazoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }// GEN-LAST:event_campoPrazoActionPerformed

    private void campoStatusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }// GEN-LAST:event_campoStatusActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {
        LocalDate dataAtual = LocalDate.now();

        String dataFormatada = dataAtual.
                format(Constantes.FORMATADOR_DATA_BR_T);

        int posicaoCursor = campoComentários.getCaret().getDot();

        campoComentários.insert(dataFormatada, posicaoCursor);
    }// GEN-LAST:event_btDataActionPerformed

    private void btHoraActionPerformed(java.awt.event.ActionEvent evt) {
        LocalTime horaAtual = LocalTime.now();

        String horaFormatada = horaAtual.format(Constantes.FORMATADOR_HORA_BR_T);

        int posicaoCursor = campoComentários.getCaret().getDot();

        campoComentários.insert(horaFormatada, posicaoCursor);
    }// GEN-LAST:event_btHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoEditarTarefa.class.
                    getName()).log(java.util.logging.Level.SEVERE,
                            null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoEditarTarefa dialog = new DialogoEditarTarefa(null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JFormattedTextField getCampoId() {
        return campoId;
    }
    //
    // public DialogoNovaTarefaController getContro() {
    // return contro;
    // }

    public JButton getBotaoCancelar() {
        return botaoCancelar;
    }

    public JButton getBotaoConcluido() {
        return botaoConcluido;
    }

    public BeanDatePick getCampoDataAl() {
        return campoDataAl;
    }

    public BeanDatePick getCampoDataFazer() {
        return campoPrazo;
    }

    public JSpinner getCampoPrioridade() {
        return campoPrioridade;
    }

    public JTextArea getCampoTitulo() {
        return campoTitulo;
    }

    public ButtonGroup getGrupoDataFazer() {
        return grupoDataFazer;
    }

    public JLabel getRotuloPriori() {
        return rotuloPriori;
    }

    public JFormattedTextField getCampoHoraAl() {
        return campoHoraAl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick beanDatePick1;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConcluido;
    private javax.swing.JButton btData;
    private javax.swing.JButton btHora;
    private javax.swing.JTextArea campoComentários;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoDataAl;
    private javax.swing.JFormattedTextField campoHoraAl;
    private javax.swing.JFormattedTextField campoId;
    private javax.swing.JComboBox<Tarefa> campoPosicao;
    private br.com.antoniodiego.gertarefas.beans.BeanDatePick campoPrazo;
    private javax.swing.JSpinner campoPrioridade;
    private javax.swing.JTextField campoStatus;
    private javax.swing.JTextArea campoTitulo;
    private javax.swing.ButtonGroup grupoDataFazer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rotuloPriori;
    // End of variables declaration//GEN-END:variables
}
